# Generated by Django 5.0.4 on 2024-04-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_alter_recipe_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_field',
            field=models.ImageField(upload_to='recipe/'),
        ),
    ]
